maplibre/maplibre-native-qt

- src/qgeomapmaplibregl.cpp
- src/qgeomapmaplibregl.h
- src/qgeoserviceproviderpluginmaplibregl.cpp
- src/qgeoserviceproviderpluginmaplibregl.h
- src/qmaplibreglstylechange.cpp
- src/qsgmaplibreglnode.cpp
- properly handle `copyrightsChanged` signal
- remove unneeded casting
- prefer `nullptr` over 0
- declare overriden methods
> Cleanup based on upstream code

- src/qsgmaplibreglnode.cpp
Reset OpenGL state also before rendering MapLibre in Qt 6 to make sure there is no unwanted interference.
> Reset state before rendering MapLibre

- .github/workflows/Android-Qt5.yml
- .github/workflows/Android-Qt6.yml
- .github/workflows/Linux-Qt6.yml
- .github/workflows/Windows-Qt5.yml
- .github/workflows/Windows-Qt6.yml
- .github/workflows/iOS-Qt5.yml
- .github/workflows/iOS-Qt6.yml
- .github/workflows/macOS-Qt5.yml
- .github/workflows/macOS-Qt6.yml
- README.md
- src/qgeomapmaplibregl.cpp
- src/qgeomapmaplibregl.h
- src/qgeomapmaplibregl_p.h
- src/qgeoserviceproviderpluginmaplibregl.h
- src/qmaplibreglstylechange.cpp
- src/qmaplibreglstylechange_p.h
- src/qsgmaplibreglnode.cpp
- src/qsgmaplibreglnode.h
Preliminary Qt 6.5 support. This temporarily removes custom parameters feature as it has been removed from upstream Qt release.
Some additional API fixes are done based on the feedback from the Qt community.
A disclaimer is added to README as things will be moving around a bit in the next weeks.
> Preliminary Qt 6.5 support

- .github/actions/qt5-build/entrypoint.sh
- .github/workflows/Android-Qt5.yml
- .github/workflows/CI-cache-cleanup.yml
- .github/workflows/Linux-Qt5.yml
- .github/workflows/Windows-Qt5.yml
- .github/workflows/iOS-Qt5.yml
- .github/workflows/macOS-Qt5.yml
- .gitmodules
- CMakeLists.txt
- README.md
- maplibregl.pro
Rename `maplibre-gl-native` to `maplibre-native` and move to vendor.
> Rename maplibre-gl-native to maplibre-native and move to vendor

- .clang-format
- .pre-commit-config.yaml
- examples/minimal/main.cpp
- src/core/geojson_p.hpp
- src/core/map_renderer_p.hpp
- src/core/renderer_backend.cpp
- src/core/utils.cpp
- src/location/plugins/qml_types.hpp
- src/location/qgeomap.cpp
- src/location/qgeomap_p.hpp
- src/location/qt_mapping_engine.cpp
- src/location/qt_mapping_engine.hpp
- src/location/stylechange.cpp
- src/location/stylechange_p.h
Add the same base `clang-format` config as in the main `maplibre-native` repo, with the exception of include sorting.
> Add clang-format config and enable pre-commit

- .github/workflows/Linux.yml
- README.md
Implement a hacky solution to ignore Qt-provided ICU (https://github.com/maplibre/maplibre-native/pull/1813, for now in the staging branch) and also add disclaimer to the README.
> Improve handling of system ICU on Linux

- README.md
- src/location/CMakeLists.txt
- src/location/plugins/CMakeLists.txt
- test/qml/CMakeLists.txt
- test/widgets/CMakeLists.txt
Fix old Qt version support for usage in linux distributions. Basically just use version specific Qt targets and one minor fix in the core.
> Fix old Qt version support for usage in linux distributions

- CMakeLists.txt
- cmake/helpers.cmake
- src/config.cmake.in
- src/core/CMakeLists.txt
- src/location/CMakeLists.txt
- src/location/plugins/CMakeLists.txt
- src/location/qgeomap.cpp
- src/widgets/CMakeLists.txt
- src/widgets/gl_widget.cpp
- test/core/CMakeLists.txt
- test/qml/CMakeLists.txt
- test/widgets/CMakeLists.txt
Add CMake helper functions for header generation and properly propagate compiler options. Some compiler warnings needed to be fixed then.
> Add CMake helper functions and properly propagate compiler options

- examples/quick/main.qml
- src/core/CMakeLists.txt
- src/core/map.cpp
- src/core/map.hpp
- src/core/map_p.hpp
- src/core/settings.cpp
- src/core/settings.hpp
- src/core/settings_p.hpp
- src/core/types.hpp
- src/location/qgeomap.cpp
- src/location/qt_mapping_engine.cpp
- src/widgets/gl_widget.cpp
- test/core/map_tester.cpp
- test/core/test_core.cpp
- test/qml/qt5/tst_map.qml
- test/qml/qt5/tst_plugin_style.qml
- test/qml/qt6/tst_map.qml
- test/qml/qt6/tst_plugin_no_parameters.qml
- test/qml/qt6/tst_plugin_provider.qml
- test/qml/qt6/tst_plugin_style.qml
- test/widgets/test_widgets.cpp
Rework style settings and make `QMapLibre::Settings` more future-proof by using private class for data storage.
A lot of work has been put into more flexible settings for QML plugin. Now most of the `QGeoMapType` properties can be set by providing JSON array as a value for `maplibre.map.styles`. A C++ equivalent of `QMapLibre::Style` is available. If unknown top-level parameters are set a warning is printed.
Provider `defaultStyles` are now renamed as `providerStyles` and are also removed from the main `QMapLibre::Map` class. By default no style is available. One can now also set a list of styles in `QMapLibre::Settings` to be used by widgets. Furthermore default coordinate and zoom level can be set.
This is in principle breaking change but it's a good time to do it now.
Closes #38 …
> Rework style settings and make QMapLibre::Settings more future-proof

- .github/actions/qt5-build/Dockerfile
- .github/actions/qt6-build/Dockerfile
Use more explicit build image names so that we stay with the required versons of build tools.
> Linux: Use more explicit build image names

- examples/.clang-tidy
- examples/quick/CMakeLists.txt
- examples/quick/main.cpp
- examples/quick/main.qml
- examples/widgets/CMakeLists.txt
- examples/widgets/main.cpp
- examples/widgets/mainwindow.cpp
- examples/widgets/mainwindow.hpp
- examples/widgets/window.cpp
- examples/widgets/window.hpp
Improve examples from the code point of view. Instructions will come in a separate PR.
- unify CMake style
- run `clang-tidy` on the examples
- add the new style options to QML
/cc @cgalvan
> Improve examples from the code point of view

- .github/workflows/iOS.yml
The patches needed for iOS ccache to work efficiently are now in a stable upstream release.
> iOS: stable version of ccache can now be used

- src/core/map.cpp
- src/core/style/layer_style_change.cpp
Properly handle layer ID separately. This was missed during the API unification. Fixes #93.
> Properly handle layer ID separately

- src/core/CMakeLists.txt
With this change I can add this project with "add_subdirectory" and just use it with just QMapLibre::Widgets in the target_link_libraries.
I am only using QT Widgets with set(MLN_QT_WITH_LOCATION OFF), so my patch probably does not fix QML builds.
> Allow to use as a cmake included project

- CMakeLists.txt
- src/core/CMakeLists.txt
- src/location/CMakeLists.txt
- src/location/plugins/CMakeLists.txt
- src/widgets/CMakeLists.txt
Add ability to build as static libraries. Fixes #77.
> Add ability to build as static libraries

- src/core/types.hpp
This helps solves the problem of compiling with Qt 5.12, making it possible to create `Styles` with `QVector`
> Create struc `Style` with empty url possible

- .github/workflows/Android.yml
- .github/workflows/Linux.yml
- .github/workflows/Windows.yml
- .github/workflows/iOS.yml
- .github/workflows/macOS.yml
Update to recently released Qt 6.6.2.
> Update to Qt 6.6.2

- src/core/CMakeLists.txt
- src/location/CMakeLists.txt
- src/widgets/CMakeLists.txt
Soversion should only reflects the major version, since the soname
link cannot be created due to equal name as the library. Library
libQMaplibre.so.3.0.0 prevents soname libQMaplibre.so.3.0.0 from being
created.
> Set proper soversion.

- CMakeLists.txt
- src/core/CMakeLists.txt
- src/location/CMakeLists.txt
- src/location/plugins/CMakeLists.txt
- src/widgets/CMakeLists.txt
- test/core/CMakeLists.txt
- test/qml/CMakeLists.txt
- test/widgets/CMakeLists.txt
Use less generic target names to allow usage as subproject:
- `Core` -> `MLNQtCore`
- `Location` -> `MLNQtLocation`
- `Widgets` -> `MLNQtWidgets`
- `CompilerOptions` -> `MLNQtCompilerOptions`
Fixes #118.
/cc @dpaulat
> Use less generic target names to allow usage as subproject

- .github/workflows/Windows.yml
- CMakeLists.txt
Fix artifact names during deployment:
- `QT_VERSION` needs to be set
- Version notation with the `v` prefix is used.
> Fix artifact names during deployment

- examples/quick/main.qml
- src/location/macros.cmake
- src/location/plugins/CMakeLists.txt
- src/location/plugins/legacy/qml_module.cpp
- src/location/plugins/legacy/qml_registration.cpp
- src/location/plugins/legacy/qmldir.in
- src/location/plugins/qmldir.in
- test/qml/qt5/tst_map.qml
- test/qml/qt5/tst_style_parameters.qml
- test/qml/qt6/tst_map.qml
- test/qml/qt6/tst_style_parameters.qml
Make MapLibre QML module namespace independent of QtLocation to prevent potential deployment issues. The syntax now changes from `import QtLocation.MapLibre 3.0` to just `import MapLibre 3.0`.
> Make MapLibre QML module namespace independent of QtLocation

- src/core/map.cpp
Update to the latest version of MapLibre Core (OpenGL 2 branch) which fixes many compilation warnings and issues.
> Update to the latest version of MapLibre Core (OpenGL 2 branch)

- .github/actions/qt5-build/entrypoint.sh
- .github/actions/qt6-build/entrypoint.sh
- .github/workflows/Android.yml
- .github/workflows/Linux.yml
- .github/workflows/Windows.yml
- .github/workflows/iOS.yml
- .github/workflows/macOS.yml
- cmake/presets/Android.json
- cmake/presets/Linux.json
- cmake/presets/WASM.json
- cmake/presets/Windows.json
- cmake/presets/iOS.json
- cmake/presets/macOS.json
- examples/quick/CMakePresets.json
- examples/widgets/CMakePresets.json
- update to Qt 6.7.1
- update to Qt install action v4
> Update to Qt 6.7.1

- src/widgets/gl_widget.cpp
- src/widgets/gl_widget.hpp
- test/widgets/gl_tester.cpp
Add mouse events with coordinate to `GLWidget`:
```
void onMouseDoubleClickEvent(QMapLibre::Coordinate coordinate);
void onMousePressEvent(QMapLibre::Coordinate coordinate);
void onMouseReleaseEvent(QMapLibre::Coordinate coordinate);
void onMouseMoveEvent(QMapLibre::Coordinate coordinate);
```
Fixes #82.
/cc @cgalvan @wecand0
> Add mouse events with coordinate to GLWidget

- .github/workflows/Android.yml
The tarball should also contain a top-level folder like for other platforms.
> Fix combined tarball creation for Android

- docs/Doxyfile
- src/core/map.cpp
- src/core/map_observer.cpp
- src/core/map_renderer.cpp
- src/core/settings.cpp
- src/core/style/image_style_change.cpp
- src/core/style/layer_style_change.cpp
- src/core/style/source_style_change.cpp
- src/core/style/style_change.cpp
- src/core/style/style_change_utils.cpp
- src/core/types.cpp
Complete core documentation and mark private classes as private to silence warnings.
Enable warnings as errors to ensure all future public code is documented.
> Complete core documentation

- .github/workflows/docs-test.yml
- .github/workflows/gh-pages-docs.yml
- .gitignore
- docs/Doxyfile
- docs/README.md
- docs/examples/example_Style.qml
- docs/examples/snippets_Map.qml
- docs/examples/snippets_Style.qml
- docs/location/LayerParameter.qml
- docs/location/QMapLibreLocation.dox
- docs/location/SourceParameter.qml
- docs/location/Style.qml
- docs/location/StyleParameter.qml
- src/core/map.cpp
- src/core/settings.cpp
- src/core/style/layer_parameter.cpp
- src/core/style/source_parameter.cpp
- src/core/types.cpp
- src/widgets/gl_widget.cpp
Complete initial reference documentation:
- add widgets documentation
- add location documentation -> this is done manually using dummy placeholder QML files and `doxyqml`
- make sure include headers are hinted for all public C++ classes
> Complete initial reference documentation

- src/core/map.cpp
- src/core/map.hpp
- src/core/map_p.hpp
- src/location/texture_node.cpp
- src/widgets/gl_widget.cpp
- test/core/map_tester.cpp
Probably makes sense to rename OpenGL-specific (at least I think it will be) `setFramebufferObject` to `setOpenGLFramebufferObject`.
In preparation for stable 3.0 release.
> Rename setFramebufferObject -> setOpenGLFramebufferObject

- src/core/CMakeLists.txt
- src/core/conversion_p.hpp
- src/core/map.cpp
- src/core/style/filter_parameter.cpp
- src/core/style/filter_parameter.hpp
- src/core/style/layer_style_change.cpp
- src/core/style/layer_style_change_p.hpp
- src/core/style/style_change.cpp
- src/location/plugins/CMakeLists.txt
- src/location/plugins/declarative_filter_parameter.cpp
- src/location/plugins/declarative_filter_parameter.hpp
- src/location/qgeomap.cpp
- test/qml/qt6/tst_style_parameters.qml
Fix style filters setting as Qt awkwardly detects `QString` as a list so it was iterated into a list of `QChar`. Also add the following improvements:
- Add ability to remove the filter easily by setting an empty expression.
- Add a `FilterParameter` helper class.
Fixes  #104.
> Fix style filters setting

- .github/workflows/iOS.yml
Disable ccache for iOS as it does not work OK and just using a lot of space.
> Disable ccache for iOS

- CMakeLists.txt
Add support for building with LTO.
Relates to #119.
> Add support for building with LTO

- src/core/CMakeLists.txt
- src/core/style/image_parameter.cpp
- src/core/style/image_parameter.hpp
- src/core/style/image_style_change.cpp
- src/core/style/image_style_change_p.hpp
- src/core/style/source_style_change.cpp
- src/core/style/style_change.cpp
- src/core/style/style_parameter.cpp
- src/core/style/style_parameter.hpp
- src/location/plugins/CMakeLists.txt
- src/location/plugins/declarative_image_parameter.cpp
- src/location/plugins/declarative_image_parameter.hpp
- src/location/plugins/declarative_source_parameter.cpp
- test/qml/CMakeLists.txt
- test/qml/qt6/tst_style_parameters.qml
- Make sure GeoJSON is properly parsed. This is a bit hacky as it has to go `QJSValue` -> `QVariant` -> `QJsonDocument` -> `QString` and then JSON is again parsed by MapLibre, but this works. It can be improved in the future if needed.
- Add `ImageParameter` to be able to add an image from Qt resources system (or local file) directly.
Implicitly closes #145 as I can not reproduce the issue.
> Improve GeoJSON and image source handling

- .clang-tidy
- .github/workflows/Android.yml
- CHANGELOG.md
- docs/Building.md
- docs/Documentation.md
- docs/Doxyfile
- test/widgets/gl_tester.cpp
- update the changelog and add it to docs
- make it clear that the docs are for 3.0 onwards
- make CMake workflows more prominent in docs by moving them up on the page
- note that `-DCMAKE_DEFAULT_CONFIGS="all"` is needed with `Ninja Multi-Config` to build everything at once (fixes #171)
- fix build with LLVM 19
- move JDK distribution to `temurin`
> Prepare release 3.0

- .github/actions/qt6-build-legacy/Dockerfile
- .github/actions/qt6-build-legacy/action.yml
- .github/actions/qt6-build-legacy/entrypoint.sh
- .github/workflows/Android.yml
- .github/workflows/Linux.yml
- .github/workflows/Windows.yml
- .github/workflows/iOS.yml
- .github/workflows/macOS.yml
- .github/workflows/source-tarball.yml
Qt 6.8.1 bumps a bit the requirements so the following changes are done for now (others will come in separate PRs):
- Windows now uses MSVC 2022 (old releases now properly use MSVC 2019)
- GCC on Linux is bumped to version 11
- CMake needs to be 3.30 or older (for now)
> Update to Qt 6.8.1 with various minor build improvements

- src/core/settings.cpp
Fix self-assignment in the `QMapLibre::Settings` class.
Got detected by the LLVM build.
> Fix self-assignment in the QMapLibre::Settings class

- .github/workflows/Android.yml
- .github/workflows/Linux.yml
- .github/workflows/Windows.yml
- .github/workflows/iOS.yml
- .github/workflows/macOS.yml
- cmake/presets/Android.json
- cmake/presets/Linux.json
- cmake/presets/WASM.json
- cmake/presets/Windows.json
- cmake/presets/iOS.json
- cmake/presets/macOS.json
- docs/Building.md
- examples/quick/CMakePresets.json
- examples/widgets/CMakePresets.json
Update to Qt 6.8.3 and Qt 6.9.0. Also drop CI checks for older Qt 6 releases as Qt 6.8 is now the LTS one.
Ignores for unrelated CI jobs were also added.
> Update to Qt 6.8.3 and Qt 6.9.0

- .github/workflows/Windows.yml
Disable Windows Qt5 builds as the 2019 runners are no longer available.
> [ci] Disable Windows Qt5 CI due to unsupported compiler
