- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CODE-OF-CONDUCT.md
- README.md
- funding information
- issue templates
- licensing information in README.md
- code of conduct
> Improve documentation and repository metadata

- .github/actions/qt5-build/entrypoint.sh
- .github/workflows/Android-Qt5.yml
- .github/workflows/Linux-Qt5.yml
- .github/workflows/Windows-Qt5.yml
- .github/workflows/iOS-Qt5.yml
- .github/workflows/macOS-Qt5.yml
Fixes to the Android CI, minor tweaks for other platforms.
> Fixes to the CI

- src/qgeomappingmanagerenginemaplibregl.cpp
Enable client options support after core update.
> Enable client options after core update

- .github/workflows/Android-Qt6.yml
- run on fixed OS versions
- add Qt6 support
> CI: update Android jobs

- .github/actions/qt5-build/entrypoint.sh
- .github/actions/qt6-build/Dockerfile
- .github/actions/qt6-build/action.yml
- .github/actions/qt6-build/entrypoint.sh
- .github/workflows/Linux-Qt6.yml
- .github/workflows/macOS-Qt5.yml
- .github/workflows/macOS-Qt6.yml
- make sure `ccache` works on Linux
- use specific runner OS versions
- add Qt6 build
- add initial release job
> CI: update Linux and macOS jobs

- .github/workflows/Windows-Qt5.yml
- .github/workflows/Windows-Qt6.yml
- use Windows 2022
- initial Qt6 support
- initial release job
> CI: update Windows jobs

- .github/workflows/iOS-Qt6.yml
- Qt6 support
- use macOS 12
- initial release job
> CI: update iOS jobs

- .github/workflows/Android-Qt5.yml
- .github/workflows/Android-Qt6.yml
- .github/workflows/Linux-Qt5.yml
- .github/workflows/Linux-Qt6.yml
- .github/workflows/Windows-Qt6.yml
- .github/workflows/iOS-Qt5.yml
- .github/workflows/iOS-Qt6.yml
- .github/workflows/macOS-Qt5.yml
- .github/workflows/macOS-Qt6.yml
- CHANGELOG.md
Update to Qt 6.4.2.
Also add missing changelog item from a fix earlier.
> Update to Qt 6.4.2

- .github/workflows/Android-Qt5.yml
- .github/workflows/Android-Qt6.yml
- .github/workflows/Linux-Qt5.yml
- .github/workflows/Linux-Qt6.yml
- .github/workflows/Windows-Qt5.yml
- .github/workflows/Windows-Qt6.yml
- .github/workflows/iOS-Qt5.yml
- .github/workflows/iOS-Qt6.yml
- .github/workflows/macOS-Qt5.yml
- .github/workflows/macOS-Qt6.yml
Try to reduce number of ccache caches by not appending the timestamp.
> Try to reduce number of ccache caches

- .github/workflows/CI-cache-cleanup.yml
Cleanup caches when PR is closed to avoid reaching the threshold too fast.
> [ci] Cleanup caches when PR is closed

- .github/workflows/Linux-Test.yml
- .github/workflows/Linux.yml
- .github/workflows/macOS.yml
- src/location/stylechange.cpp
Fix the build with Qt 6.6 and enable Qt 6.6 in the CI.
> Fix the build with Qt 6.6

- .github/workflows/CI-cache-cleanup.yml
Cleanup caches in the target repo so that there are permissions to do it.
> [ci] Cleanup caches in the target repo

- src/core/conversion_p.hpp
- src/core/geojson.cpp
- src/core/geojson_p.hpp
- src/core/map.cpp
- src/core/map.hpp
- src/core/map_observer_p.hpp
- src/core/map_p.hpp
- src/core/map_renderer.cpp
- src/core/map_renderer_p.hpp
- src/core/scheduler_p.hpp
- src/core/settings.cpp
- src/core/settings.hpp
- src/core/types.hpp
- src/location/qt_mapping_engine.cpp
- src/widgets/gl_widget.cpp
- test/common/test_rendering.cpp
- test/common/test_rendering.hpp
- test/core/map_tester.cpp
- test/widgets/gl_tester.cpp
- test/widgets/gl_tester.hpp
Cleanup Qt headers so it's clear from which module the code comes from.
> Qt header cleanup

- CMakeLists.txt
- src/CMakeLists.txt
- src/core/CMakeLists.txt
- src/location/CMakeLists.txt
- src/location/plugins/CMakeLists.txt
- src/widgets/CMakeLists.txt
- test/CMakeLists.txt
- test/core/CMakeLists.txt
- test/qml/CMakeLists.txt
- test/widgets/CMakeLists.txt
CMake coding style unification. It's mostly manual as current formatters do not seem to be flexible enough (`gersemi` kind of worked the best, but still not ideally).
> CMake coding style unification

- .github/workflows/Android.yml
- .github/workflows/iOS.yml
- examples/quick/CMakeLists.txt
Enable Android and iOS support for Qt6.
> Add Android and iOS support

- .github/workflows/Android.yml
- .github/workflows/Linux.yml
- .github/workflows/Windows.yml
- .github/workflows/iOS.yml
- .github/workflows/macOS.yml
> Bump Qt to 6.6.1

- .github/workflows/Android.yml
- .github/workflows/Linux.yml
- .github/workflows/Windows.yml
- .github/workflows/iOS.yml
- .github/workflows/macOS.yml
Update tested Qt versions:
- Qt 6.6.2 to Qt 6.6.3
- Add Qt 6.7.0
- Update tested LLVM version to 18.1
> Update tested Qt versions

- .github/workflows/Android.yml
- .github/workflows/Linux.yml
- .github/workflows/Windows.yml
- .github/workflows/iOS.yml
- .github/workflows/macOS.yml
- test/qml/CMakeLists.txt
Update to Qt 6.7.2, including macOS static build and Android build.
> Update to Qt 6.7.2

- src/core/map.cpp
- test/qml/qt6/tst_style_parameters.qml
Support image coordinate change to avoid recreating image to just move it around.
Fixes #115 (/cc @kebekus)
> Support image coordinate change

- .github/workflows/Android.yml
- src/location/macros.cmake
- fix Android release configuration
- fix deployment macros for static builds
> Fix static and Android releases

- .github/workflows/docs-test.yml
- .github/workflows/gh-pages-docs.yml
- README.md
- docs/Documentation.md
- docs/Usage.md
- examples/quick/minimal.pro
Add usage documentation and update Doxygen to 1.12.0.
> Add usage documentation

- README.md
- cmake/presets/Linux.json
- docs/Building.md
- docs/Documentation.md
Various documentation tweaks and improvements:
- Prepare for 3.0 release.
- Add Linux workflow for building with internal ICU library.
- Mention `CMAKE_TOOLCHAIN_FILE`.
- Make per-platform examples more verbose and self-contained.
- Note `Filename too long` issue on Windows.
> Various documentation tweaks and improvements

- .github/workflows/Android.yml
- .github/workflows/Linux.yml
- .github/workflows/Windows.yml
- .github/workflows/iOS.yml
- .github/workflows/macOS.yml
- .github/workflows/source-tarball.yml
> Update to Qt 6.7.3

- docs/Building.md
Addresses https://github.com/maplibre/maplibre-native-qt/issues/199
> Docs: Add instructions on installing Qt packages
